<?php

namespace Database\Seeders;

use App\Models\Commune;
use App\Models\Region;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ChileLocationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $regions = [
            [
                'order' => 1,
                'code' => 'XV',
                'name' => 'Región de Arica y Parinacota',
                'communes' => [
                    'Arica',
                    'Camarones',
                    'Putre',
                    'General Lagos',
                ],
            ],
            [
                'order' => 2,
                'code' => 'I',
                'name' => 'Región de Tarapacá',
                'communes' => [
                    'Iquique',
                    'Alto Hospicio',
                    'Pozo Almonte',
                    'Camiña',
                    'Colchane',
                    'Huara',
                    'Pica',
                ],
            ],
            [
                'order' => 3,
                'code' => 'II',
                'name' => 'Región de Antofagasta',
                'communes' => [
                    'Antofagasta',
                    'Mejillones',
                    'Sierra Gorda',
                    'Taltal',
                    'Calama',
                    'Ollagüe',
                    'San Pedro de Atacama',
                    'Tocopilla',
                    'María Elena',
                ],
            ],
            [
                'order' => 4,
                'code' => 'III',
                'name' => 'Región de Atacama',
                'communes' => [
                    'Copiapó',
                    'Caldera',
                    'Tierra Amarilla',
                    'Chañaral',
                    'Diego de Almagro',
                    'Vallenar',
                    'Alto del Carmen',
                    'Freirina',
                    'Huasco',
                ],
            ],
            [
                'order' => 5,
                'code' => 'IV',
                'name' => 'Región de Coquimbo',
                'communes' => [
                    'La Serena',
                    'Coquimbo',
                    'Andacollo',
                    'La Higuera',
                    'Paihuano',
                    'Vicuña',
                    'Illapel',
                    'Canela',
                    'Los Vilos',
                    'Salamanca',
                    'Ovalle',
                    'Combarbalá',
                    'Monte Patria',
                    'Punitaqui',
                    'Río Hurtado',
                ],
            ],
            [
                'order' => 6,
                'code' => 'V',
                'name' => 'Región de Valparaíso',
                'communes' => [
                    'Valparaíso',
                    'Viña del Mar',
                    'Concón',
                    'Quintero',
                    'Puchuncaví',
                    'Quilpué',
                    'Villa Alemana',
                    'Limache',
                    'Olmué',
                    'Quillota',
                    'La Calera',
                    'Nogales',
                    'Hijuelas',
                    'La Cruz',
                    'San Antonio',
                    'Cartagena',
                    'El Tabo',
                    'El Quisco',
                    'Algarrobo',
                    'Santo Domingo',
                    'Petorca',
                    'Cabildo',
                    'Papudo',
                    'Zapallar',
                    'La Ligua',
                    'San Felipe',
                    'Llay-Llay',
                    'Putaendo',
                    'Santa María',
                    'Catemu',
                    'Panquehue',
                    'Los Andes',
                    'Calle Larga',
                    'Rinconada',
                    'Isla de Pascua',
                    'Juan Fernández',
                ],
            ],
            [
                'order' => 7,
                'code' => 'RM',
                'name' => 'Región Metropolitana de Santiago',
                'communes' => [
                    'Santiago',
                    'Cerrillos',
                    'Cerro Navia',
                    'Conchalí',
                    'El Bosque',
                    'Estación Central',
                    'Huechuraba',
                    'Independencia',
                    'La Cisterna',
                    'La Florida',
                    'La Granja',
                    'La Pintana',
                    'La Reina',
                    'Las Condes',
                    'Lo Barnechea',
                    'Lo Espejo',
                    'Lo Prado',
                    'Macul',
                    'Maipú',
                    'Ñuñoa',
                    'Pedro Aguirre Cerda',
                    'Peñalolén',
                    'Providencia',
                    'Pudahuel',
                    'Quilicura',
                    'Quinta Normal',
                    'Recoleta',
                    'Renca',
                    'San Joaquín',
                    'San Miguel',
                    'San Ramón',
                    'Vitacura',
                    'Colina',
                    'Lampa',
                    'Tiltil',
                    'Puente Alto',
                    'Pirque',
                    'San José de Maipo',
                    'San Bernardo',
                    'Buin',
                    'Paine',
                    'Calera de Tango',
                    'Melipilla',
                    'Alhué',
                    'Curacaví',
                    'María Pinto',
                    'San Pedro',
                    'Talagante',
                    'El Monte',
                    'Isla de Maipo',
                    'Padre Hurtado',
                    'Peñaflor',
                ],
            ],
            [
                'order' => 8,
                'code' => 'VI',
                'name' => 'Región del Libertador General Bernardo O’Higgins',
                'communes' => [
                    'Rancagua',
                    'Machalí',
                    'San Fernando',
                    'Santa Cruz',
                    'Pichilemu',
                    'Chimbarongo',
                    'Nancagua',
                    'Peralillo',
                    'Palmilla',
                    'Marchigüe',
                    'Pumanque',
                    'Lolol',
                    'Doñihue',
                    'Graneros',
                    'Requínoa',
                    'Rengo',
                    'Quinta de Tilcoco',
                    'Mostazal',
                    'Coinco',
                    'Coltauco',
                    'San Vicente',
                    'Las Cabras',
                    'Peumo',
                    'Pichidegua',
                    'La Estrella',
                    'Litueche',
                    'Navidad',
                ],
            ],
            [
                'order' => 9,
                'code' => 'VII',
                'name' => 'Región del Maule',
                'communes' => [
                    'Talca',
                    'Maule',
                    'Pelarco',
                    'Pencahue',
                    'Río Claro',
                    'San Clemente',
                    'San Rafael',
                    'Curicó',
                    'Teno',
                    'Romeral',
                    'Molina',
                    'Sagrada Familia',
                    'Hualañé',
                    'Licantén',
                    'Vichuquén',
                    'Linares',
                    'Colbún',
                    'Yerbas Buenas',
                    'Villa Alegre',
                    'Longaví',
                    'Parral',
                    'Retiro',
                    'Cauquenes',
                    'Chanco',
                    'Pelluhue',
                ],
            ],
            [
                'order' => 10,
                'code' => 'XVI',
                'name' => 'Región de Ñuble',
                'communes' => [
                    'Chillán',
                    'Chillán Viejo',
                    'Bulnes',
                    'Quillón',
                    'San Ignacio',
                    'Pemuco',
                    'El Carmen',
                    'Pinto',
                    'Coihueco',
                    'Ñiquén',
                    'San Carlos',
                    'San Fabián',
                    'San Nicolás',
                    'Quirihue',
                    'Cobquecura',
                    'Coelemu',
                    'Ninhue',
                    'Treguaco',
                    'Portezuelo',
                    'Ránquil',
                ],
            ],
            [
                'order' => 11,
                'code' => 'VIII',
                'name' => 'Región del Biobío',
                'communes' => [
                    'Concepción',
                    'Talcahuano',
                    'Hualpén',
                    'Penco',
                    'Tomé',
                    'Chiguayante',
                    'San Pedro de la Paz',
                    'Coronel',
                    'Lota',
                    'Los Ángeles',
                    'Mulchén',
                    'Nacimiento',
                    'Negrete',
                    'Cabrero',
                    'Yumbel',
                    'Laja',
                    'Tucapel',
                    'Santa Bárbara',
                    'Quilaco',
                    'Alto Biobío',
                    'Lebu',
                    'Curanilahue',
                    'Arauco',
                    'Los Álamos',
                    'Contulmo',
                    'Cañete',
                ],
            ],
            [
                'order' => 12,
                'code' => 'IX',
                'name' => 'Región de La Araucanía',
                'communes' => [
                    'Temuco',
                    'Padre Las Casas',
                    'Lautaro',
                    'Vilcún',
                    'Freire',
                    'Pitrufquén',
                    'Gorbea',
                    'Loncoche',
                    'Villarrica',
                    'Pucón',
                    'Curarrehue',
                    'Melipeuco',
                    'Cunco',
                    'Nueva Imperial',
                    'Carahue',
                    'Saavedra',
                    'Toltén',
                    'Cholchol',
                    'Angol',
                    'Collipulli',
                    'Renaico',
                    'Ercilla',
                    'Traiguén',
                    'Los Sauces',
                    'Purén',
                    'Lumaco',
                    'Victoria',
                    'Curacautín',
                    'Lonquimay',
                    'Galvarino',
                ],
            ],
            [
                'order' => 13,
                'code' => 'XIV',
                'name' => 'Región de Los Ríos',
                'communes' => [
                    'Valdivia',
                    'Corral',
                    'Mariquina',
                    'Lanco',
                    'Máfil',
                    'Paillaco',
                    'Los Lagos',
                    'Futrono',
                    'Lago Ranco',
                    'Río Bueno',
                    'La Unión',
                ],
            ],
            [
                'order' => 14,
                'code' => 'X',
                'name' => 'Región de Los Lagos',
                'communes' => [
                    'Puerto Montt',
                    'Puerto Varas',
                    'Llanquihue',
                    'Frutillar',
                    'Fresia',
                    'Los Muermos',
                    'Calbuco',
                    'Maullín',
                    'Cochamó',
                    'Osorno',
                    'San Pablo',
                    'San Juan de la Costa',
                    'Puyehue',
                    'Río Negro',
                    'Purranque',
                    'Chonchi',
                    'Castro',
                    'Dalcahue',
                    'Curaco de Vélez',
                    'Quinchao',
                    'Queilén',
                    'Quellón',
                    'Puqueldón',
                    'Ancud',
                    'Quemchi',
                    'Chaitén',
                    'Futaleufú',
                    'Palena',
                ],
            ],
            [
                'order' => 15,
                'code' => 'XI',
                'name' => 'Región de Aysén del General Carlos Ibáñez del Campo',
                'communes' => [
                    'Coyhaique',
                    'Lago Verde',
                    'Aysén',
                    'Cisnes',
                    'Guaitecas',
                    'Chile Chico',
                    'Río Ibáñez',
                    'Cochrane',
                    'Tortel',
                    'O’Higgins',
                ],
            ],
            [
                'order' => 16,
                'code' => 'XII',
                'name' => 'Región de Magallanes y de la Antártica Chilena',
                'communes' => [
                    'Punta Arenas',
                    'Río Verde',
                    'Laguna Blanca',
                    'San Gregorio',
                    'Porvenir',
                    'Primavera',
                    'Timaukel',
                    'Puerto Natales',
                    'Torres del Paine',
                    'Cabo de Hornos',
                    'Antártica',
                ],
            ],
        ];

        foreach ($regions as $regionData) {
            $region = Region::updateOrCreate(
                ['code' => $regionData['code']],
                [
                    'name' => $regionData['name'],
                    'slug' => Str::slug($regionData['name']),
                    'order' => $regionData['order'],
                ]
            );

            foreach ($regionData['communes'] as $name) {
                $slug = Str::slug($name);

                $commune = Commune::updateOrCreate(
                    ['slug' => $slug],
                    [
                        'region_id' => $region->id,
                        'name' => $name,
                    ]
                );

                if ($commune->region_id !== $region->id) {
                    $commune->region()->associate($region);
                    $commune->save();
                }
            }
        }
    }
}
